<?php

declare(strict_types=1);

namespace App\Services;

use App\Contracts\AiServiceContract;
use Illuminate\Support\Facades\Log;

final class MockAiService implements AiServiceContract
{
    /**
     * Generate a mock AI response.
     */
    public function generateChatResponse(string $message, array $history = [], ?string $reportUrl = null): string
    {
        Log::info('Mock AI Service called to generate response', [
            'message' => $message,
            'has_report' => $reportUrl !== null,
        ]);

        $normalizedMessage = strtolower(trim($message));

        if ($this->containsAny($normalizedMessage, ['hello', 'hi', 'hey', 'greetings'])) {
            return "Hello! I'm your AMRV medical assistant. I can help explain your medical reports, track health trends, or answer general wellness questions. How can I help you today?";
        }

        if ($this->containsAny($normalizedMessage, ['report', 'blood', 'test', 'result', 'pdf', 'image', 'scan'])) {
            if ($reportUrl !== null) {
                return "I've reviewed the linked medical document. The majority of your blood markers and vital signs are within reference limits. However, I noticed some slight fluctuations. Would you like me to explain any specific metrics or terms, such as Cholesterol, HbA1c, or RBC count?";
            }
            return "Please link or refer to a specific medical report, and I'll analyze the details, summarize the risks, and provide actionable health recommendations.";
        }

        if ($this->containsAny($normalizedMessage, ['emergency', 'pain', 'hurts', 'chest', 'breathing', 'severe'])) {
            return "WARNING: If you are experiencing severe symptoms, chest pain, or breathing difficulties, please call emergency services immediately or contact your emergency contact. I am an AI helper and cannot replace professional medical diagnosis.";
        }

        if ($this->containsAny($normalizedMessage, ['thank', 'thanks', 'cool', 'awesome'])) {
            return "You're very welcome! If you have any other questions about your health reports or need help understanding wellness advice, feel free to ask.";
        }

        // Generic mock response
        return "This is a placeholder response from the Mock AI Service. Once the Flask backend or AI SDK is configured and bound in AppServiceProvider, this message will be generated by the real model. Let me know if you need help with anything else!";
    }

    /**
     * Check if the message contains any of the search terms.
     */
    private function containsAny(string $message, array $terms): bool
    {
        foreach ($terms as $term) {
            if (str_contains($message, $term)) {
                return true;
            }
        }
        return false;
    }
}
